name: Refresh Strava Credentials1

on:
  schedule:
    - cron: '0 0 * * 0' # Chaque dimanche à minuit
  workflow_dispatch: {} # Déclenchement manuel

jobs:
  refresh-creds:
    runs-on: ubuntu-latest
    name: Refresh Strava Credentials
    steps:
      - uses: actions/checkout@v3 # Clone le dépôt

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm install playwright
          npx playwright install --with-deps

      - name: Fetch Strava credentials
        env:
          STRAVA_EMAIL: ${{ secrets.STRAVA_EMAIL }}
          STRAVA_PASSWORD: ${{ secrets.STRAVA_PASSWORD }}
        run: |
          node ./scripts/refresh_strava_credential1.js >> $GITHUB_ENV

      - name: Mask sensitive data
        run: |
          echo "::add-mask::${STRAVA_ID}"
          echo "::add-mask::${STRAVA_COOKIES}"

      - name: Write Strava creds to Cloudflare
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            STRAVA_ID
            STRAVA_COOKIES
